### ISSUE TITLE
single file .vue formatting no longer works correctly

### ISSUE THREAD

**Issue by frudman** [vuejs/vetur#1189]
## Info

- Platform: Mac (el capitan)
- Vetur version: 0.18.1 (2019-04-04)
- VS Code version: 1.33.0 (updated 4/4/2019)

## Problem

After update of either Vetur (updated 4/4) or VS Code (also updated/restarted 4/4), the formatting of single-file .vue code is no longer correct (was fine until then).

I attached a snapshot of current display. Unfortunately I do not have an earlier snapshot of the correct formatting (since it was working!).

## Reproducible Case

Not sure how you can reproduce it. I've closed down VSCode, restarted it. Closed code tab, reopened it. Still same [new] result. 

Formatting is incorrect. Incorrect formatting is same after close/reopen. Starts right at **icon** closing tag (white), through closing **h4** tag, through start of **form** below. Then seems ok/not-ok for rest of template.

Ditto for actual code (**script**) where color coding fails and most of the code is just white text.

All else is working fine, code is compiling/executing correctly. No other issues other than annoying (and now hard to use) formatting.

Formatting of STYLE is fine (using stylus on this file, in case that's relevant).

## template issue
![Screen Shot 2019-04-07 at 10 14 39 AM](https://user-images.githubusercontent.com/5420101/55684875-5adf8600-591e-11e9-92f5-c8f95088eef3.png)

## script issue
![Screen Shot 2019-04-07 at 10 14 17 AM](https://user-images.githubusercontent.com/5420101/55684876-5adf8600-591e-11e9-9175-7117d5deb7f3.png)

**Comment by sgehrman** [comment]
I just updated VSCode and now it says View Language Server crashed every time I save.

**Comment by hushiking** [comment]
you could try to install vetur 0.18.1 version

**Comment by prinzt** [comment]
Rollback to 0.18.0 fixes the issue for me.

**Comment by sgehrman** [comment]
Me too

**Comment by octref** [comment]
Can you give one full file on which I can fully repro this issue?

**Comment by frudman** [comment]
yesm i'm happy to **private-send** you a file (but i don't want it published on forums). u can email me your email. not sure how to do private messages on github. (ps: still have problem today after full restart of everything).

**Comment by octref** [comment]
@frudman I sent you an email.

**Comment by frudman** [comment]
sorry, already sent to your email. did you get it?

**Comment by octref** [comment]
@frudman I got it.

Syntax highlighting is broken because you need to use quotes around interpolations. In line 18, something like this would do:

```html
<h4><icon v-if="foo" bar :hover="bar" /></h4>
```

The quoteless HTML attribute usage would cause problems. This has never been working:

```html
<h4><icon v-if=foo bar :hover=bar /></h4>
```

As for formatting, what's your config for `vetur.format.defaultFormatter.html`?

**Comment by frudman** [comment]
thanks for looking into this. a couple of points:

1) html/5 does not require quotes around simple attr values, afaik. perhaps vue or vetur does? (or is this a newer req?) (or newly enforced req?)
2) this was never an issue in the past. all our components are coded like that. And none had this problem before. 

I don't see a vetur config file in my project (or home directory). I'm on a mac. Is it kept somewhere else? Either that, or I'm using it with standard options.

**Comment by octref** [comment]
> html/5 does not require quotes around simple attr values

That's right, but Vue interpolations are not simple attribute values. That code itself wouldn't even be valid HTML5:

https://mathiasbynens.be/notes/unquoted-attribute-values

![image](https://user-images.githubusercontent.com/4033249/55754996-c6028880-5a02-11e9-8b1e-82c87b299342.png)

You can read https://code.visualstudio.com/docs/getstarted/settings to better understand VS Code settings. By default Vetur uses https://prettyhtml.netlify.com/ for template formatting. If that doesn't work for you, you can either disable it with `vetur.format.defaultFormatter.html: "none"` or use another formatter: https://vuejs.github.io/vetur/formatting.html#formatters.

**Comment by frudman** [comment]
agreed about the [classic] foo bar example: we do use quotes when attr vals contain spaces, '=', or other such char (which for us is rare, but for which you can see an example of this in code i sent). 

**so, bottom line, for us to use vetur, quotes are required always, is that correct?**

(out of curiosity, why was this not an issue until recently (at least not for us/our code)? or even last update? was it vetur update or vscode update? just curious)

**Comment by octref** [comment]
There's no spec that says you can or cannot use unquoted attributes. But currently the Textmate grammar of Vetur doesn't support unquoted values very well.

> why was this not an issue until recently

For which version of Vetur / VS Code does this work? I tested on 1.18.0 but syntax highlighting still didn't work.

**Comment by frudman** [comment]
ok.

we use latest version of software, always. vs code & vetur (& others). only recent update was vetur (&, coincidentally) vs code on same day (4/4/2019). prior to that, all was well: i assume vetur was at 0.18.0 (but never checked) and vs code was at whichever version before 1.33 (i'm assuming 1.32.0)

it's not a big deal. we just liked using vetur. it made code nice-and-easy for us to read on screen. 

no worries.

[ps: prior version of vetur did work for us, at least syntax coloring did]

**Comment by octref** [comment]
You can get old downloads here: https://code.visualstudio.com/updates/v1_32 and old Vetur releases in https://github.com/vuejs/vetur/releases. https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix is how to install them.

**Comment by octref** [comment]
The syntax highlighting for unquoted attributes should be fixed in https://github.com/vuejs/vetur/pull/1193.

**Comment by frudman** [comment]
that's great! can't wait for next version to be released!
Thanks again for all your work.

**Comment by thalysmg** [comment]
How can I install vetur 0.18.0? Or change 0.19.0 to 0.18.0??

**Comment by ConorSheehan1** [comment]
Still seeing this issue with v0.22.6, but only for large .vue files.
![Screenshot 2020-01-09 at 11 23 12](https://user-images.githubusercontent.com/16896053/72063945-b934fd00-32d2-11ea-97ce-9f765ef6279d.png)

![Screenshot 2020-01-09 at 11 28 34](https://user-images.githubusercontent.com/16896053/72064159-319bbe00-32d3-11ea-8e06-9c2c806709ce.png)

**Comment by ConorSheehan1** [comment]
Finally got it fixed, by this comment https://github.com/vuejs/vetur/issues/543#issuecomment-397819763

> Mine is fixed.
> 
> 1. Install Prettier extension.
>    URL - https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode
> 2. Go to File > Preferences > Settings
> 3. Add below,
>    "prettier.singleQuote": true,
>    "prettier.semi": false,
>    "prettier.eslintIntegration": true
> 4. Save.
> 5. Try Alt + Shift + F

but without "prettier.eslintIntegration", since it's deprecated now.

**Comment by andrewhood** [comment]
A workaround that worked for me: 
1. copy paste the original file into the same folder
2. delete the original file
3. rename the new file to what the original file was named
