### ISSUE TITLE
Vetur cannot use Prettier installed via Yarn Berry (PnP)

### ISSUE THREAD

**Issue by bkarlson** [vuejs/vetur#2092]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: MacOS
- Vetur version: 0.25.0
- VS Code version:  1.47.2

## Problem

I'm using Yarn 2.1.1, and installed Prettier using official manual: https://next.yarnpkg.com/advanced/editor-sdks/

Yarn installs packages within `.yarn` folder, and Vetur cannot find Prettier in such case:

```
[Error - 1:00:16 AM] Cannot find module 'prettier' from '/workspace/package.json'
```

If I unplug the package and move `node_modules` from `.yarn` into the workspace root, Vetur works fine. 

I assume Vetur is not 100% PnP compatible, at least when it comes to Prettier (maybe some other libs too).

**Comment by yoyo930021** [comment]
Follow #1711

**Comment by merceyz** [comment]
The fix here, just as with typescript, is to respect the `prettier.prettierPath` config

**Comment by yoyo930021** [comment]
I open a new issue #2469 .
Now the bundled version will be used if prettier can't be found.

**Comment by yoyo930021** [comment]
Fixed #2478

**Comment by merceyz** [comment]
I did not fix this issue in #2478

**Comment by yoyo930021** [comment]
> I did not fix this issue in #2478 , the code that looks for prettier does not use `require.resolve` so it doesn't work under PnP

The error is solve.

The prettier part write in documention.
https://vuejs.github.io/vetur/guide/setup.html#yarn-pnp

**Comment by bkarlson** [comment]
@yoyo930021 , I still cannot make Prettier work with Vetur (works with everything else though):

```
Prettier format failed
[Error - 9:04:26 PM] Error: Your application tried to access prettier, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: prettier (via "prettier")
Required by: /Volumes/Backup/home/Documents/src/components/My/MyTabs.vue/

Require stack:
- /Volumes/Backup/home/.vscode/extensions/octref.vetur-0.31.3/server/dist/vls.js
- /Volumes/Backup/home/.vscode/extensions/octref.vetur-0.31.3/server/dist/vueServerMain.js
    at internalTools_makeError (/Volumes/Backup/home/Documents/.pnp.js:21850:34)
    at resolveToUnqualified (/Volumes/Backup/home/Documents/.pnp.js:22809:23)
    at resolveRequest (/Volumes/Backup/home/Documents/.pnp.js:22907:29)
    at Object.resolveRequest (/Volumes/Backup/home/Documents/.pnp.js:22985:26)
    at Function.external_module_.Module._resolveFilename (/Volumes/Backup/home/Documents/.pnp.js:22083:34)
    at Function.resolve (internal/modules/cjs/helpers.js:80:19)
    at Object.get (/Volumes/Backup/home/.vscode/extensions/octref.vetur-0.31.3/server/dist/vls.js:576:3728)
    at prettierify (/Volumes/Backup/home/.vscode/extensions/octref.vetur-0.31.3/server/dist/vls.js:577:754)
    at Object.format (/Volumes/Backup/home/.vscode/extensions/octref.vetur-0.31.3/server/dist/vls.js:610:3079)
    at /Volumes/Backup/home/.vscode/extensions/octref.vetur-0.31.3/server/dist/vls.js:866:3932
Prettier format failed
[Error - 9:04:30 PM] Error: Your application tried to access prettier, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.
```

Tried installing both into root workspace and project workspace, played with `  "prettier.prettierPath": ".yarn/pnpify/prettier/index.js"` and unplugged Prettier -- nothing works with Vetur.

This line from the docs is super ambigious:

> Prettier don't support yarn pnp, so can't load plugin automatic.

Does it mean users need to load plugin (which?) manually (how??). Prettier supports pnp afaik, at least it works with other filetypes in VSCode.

**Comment by yoyo930021** [comment]
I am not familiar with PnP.
If anyone can help, the PR is welcome.
