### ISSUE TITLE
Supporting <script setup>

### ISSUE THREAD

**Issue by boonyasukd** [vuejs/vetur#2296]
- [x] I have searched through existing issues

## Feature Request

Earlier this year Evan [introduced a new RFC](https://github.com/vuejs/rfcs/pull/182) to improve upon the script section to support `<script setup>`. This RFC is already included as part of the `vue@next`, and `vue-loader` was recently updated to support it, so it's my hope that `vetur` will update to support this as well, since without it intellisense doesn't work correctly. The error I got was

```
File '/path/to/component/HelloWorld.vue' is not a module. Vetur(2306)
```

<img width="887" alt="Screen Shot 2020-09-21 at 00 22 58" src="https://user-images.githubusercontent.com/8109816/93717567-d24fb680-fba0-11ea-8f5f-9ff7ef30dba0.png">

**Comment by cereschen** [comment]
nice but hack

**Comment by akai007** [comment]
one more could support. like bellow:
`
<script setup="props, { emit }" lang="ts">
export const handleClick = (evt) => {
  emit('click', evt);
};
</script>
`
![image](https://user-images.githubusercontent.com/10443550/93730324-b7119500-fbfa-11ea-816b-529602995a7a.png)

**Comment by yoyo930021** [comment]
This feature need to add wrapper code like template Interpolation.

**Comment by soerenmartius** [comment]
async setup should be considered also, e.G.

**SomeComponent.vue**
```
<template>
  <Container title="Domains">
    <template #breadcrumb>
      <Breadcrumb
        :routes="[
          { title: 'Dashboard', name: Routes.DASHBOARD },
          { title: 'Domains', name: Routes.DOMAIN_LIST },
        ]"
      />
    </template>
    <template #content>
      <Table />
    </template>
  </Container>
</template>

<script lang="ts" async setup>
export { default as Container } from '@/modules/ui/components/Container.vue'
export { default as Table } from '@/modules/domain/components/domain/Table.vue'
export { default as Breadcrumb } from '@/modules/ui/components/Breadcrumb.vue'
export { Routes } from '@/router'

export default {}
</script>
```

**Comment by fajuchem** [comment]
When using export default it also not recognize props.

**Component.vue**
````js
<template>
  <h1>{{ msg }}</h1>
  <button @click="count++">count is: {{ count }}</button>
</template>

<script setup="props" lang="ts" async>
import { ref } from 'vue';

export default {
  props: {
    msg: {
      type: String,
      default: 'default msg',
    },
  },
};

console.log(props.msg); // Cannot find name 'props'.Vetur(2304)

export const count = ref(0);
</script>
```

**Comment by Ambyjkl** [comment]
I don't know how the language server is implemented underneath, but `@vue/compiler-sfc` already supports this, so it would just be a matter of using it to codegen the required information.

**Comment by yoyo930021** [comment]
> I don't know how the language server is implemented underneath, but `@vue/compiler-sfc` already supports this, so it would just be a matter of using it to codegen the required information.

It's actually not that simple.
It involves monorepo support and code conversion.
This will be my next job after monorepo support.

**Comment by Uninen** [comment]
Is there a way to disable `<script setup>`-related errors in Vetur / work around them somehow without turning off all validations? Would like to upgrade my code to the new syntax.

I know it's very early days still, Thank You all for your hard work with Vetur 👍

**Comment by boonyasukd** [comment]
@Uninen If you look at recent changes made to vitepress, Evan seems to [suggest the team to use Volar instead of Vetur for now](https://github.com/vuejs/vitepress/pull/137#issuecomment-733868635), so maybe you can try using that until Vetur is up-to-date.

**Comment by CaptainYouz** [comment]
yo. Any news on this one ?

**Comment by xon52** [comment]
2 month bump 🎂

**Comment by cweijan** [comment]
+1.

**Comment by web2033** [comment]
https://twitter.com/NikhilVerma/status/1405199735107973120 + reply

**Comment by arafatamim** [comment]
Now that Vue 3.2 is out with stable support for this, is this landing soon?

**Comment by zynth17** [comment]
any update about this?

**Comment by boonyasukd** [comment]
@zynth17, @arafatamim, and others

If you take a look at how Evan recently [responded](https://github.com/vuejs/rfcs/discussions/378#discussioncomment-1158805) about the recommended approach going forward, it seems that [volar](https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar) is currently the extension of choice for vue 3. 

I've been using volar for several months, and so far the auto-completion in both `<script>` and `<template>` section has been nice. It's doubly nice if the component library you use is developed in TS and provide thorough typing information for VLS to work things out, since it catches a lot of misspellings, and you can simply hover your mouse to see type info of each variable:

<img width="720" alt="Screen Shot 2021-09-09 at 11 50 09" src="https://user-images.githubusercontent.com/8109816/132624814-5b41705f-8e75-40c8-87a3-1ff10170c4c4.png">

**Comment by zynth17** [comment]
> @zynth17, @arafatamim, and others
> 
> If you take a look at how Evan recently [responded](https://github.com/vuejs/rfcs/discussions/378#discussioncomment-1158805) about the recommended approach going forward, it seems that [volar](https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar) is currently the extension of choice for vue 3.
> 
> I've been using volar for several months, and so far the auto-completion in both `<script>` and `<template>` section has been nice. It's doubly nice if the component library you use is developed in TS and provide thorough typing information for VLS to work things out, since it catches a lot of misspellings, and you can simply hover your mouse to see type info of each variable:
> 
> <img alt="Screen Shot 2021-09-09 at 11 50 09" width="720" src="https://user-images.githubusercontent.com/8109816/132624814-5b41705f-8e75-40c8-87a3-1ff10170c4c4.png">

i do love volar but what i dont like from volar is it doesn't support the autoclosing tag
you need to close bracket, or parentheses even quote manually. it's just very annoying to do it manually

**Comment by ivan-bragin** [comment]
@boonyasukd Does that mean that Vetur has no close plans to implement `<script setup>` any time soon?

**Comment by boonyasukd** [comment]
@ivan-bragin That I don't really know. I'm just a regular vue user who happens to follow Evan closely on Twitter and Github, so I noticed the change in recommendation. If you want to know that, you probably have to ask vetur maintainer(s).

**Comment by zxhhh11** [comment]
I have two solutions to avoid this error for now 
1. change <script setup></script>  to 
<script>
import { defineComponent } from 'vue';

export default defineComponent({
  setup() {
  }
});
</script>
2.  Add a script tag at the top of the Vue file to declare the name attribute
<script lang="ts">
export default {
  name: 'NavBar'  //  this method will resolve the error ：“Module  ...  has no default export.Vetur(1192)”
};
</script>
<script lang="ts" setup>
</script>

**Comment by goshander** [comment]
Can just disable Vetur for script section and use ESlint, TSLint

VS Code JSON config line
`"vetur.validation.script": false,`

**Comment by wahyubucil** [comment]
> For now can just disable Vetur for script section and use ESlint, TSLint
> 
> VS Code JSON config line `"vetur.validation.script": false,`

Currently, I had Vue 2 project but using the <script setup>, and using Volar is bad, it always "heap out of memory". So using Vetur is a good choice for now.

And disabling script validation working at least for now.
If you're using Typescript, it's recommended to disable interpolation validation too.
`"vetur.validation.interpolation": false`
The error on the template will be gone. We don't get any autocomplete on the template, but it's okay for now, we still can use runtime error for that.

**Comment by tomcorey26** [comment]
Just a heads up if you installed volar to get the setup support it seems like you also have to uninstall vetur as well in order to get it to work. (at least thats what I had to do)

**Comment by Miguel-Bento-Github** [comment]
> Just a heads up if you installed volar to get the setup support it seems like you also have to uninstall vetur as well in order to get it to work. (at least thats what I had to do)

Yeah, the best is to create a workspace with Vetur disabled, it might be that you have projects without the `setup` script.

**Comment by tarkhil** [comment]
`<script setup="">` works. I've found no other working solution so far

**Comment by bodograumann** [comment]
You should be using volar nowadays. It has superseded vetur afaik.
I don’t think it makes much sense to also implement setup support here.
What are the official plans for vetur, @octref, @yoyo930021?

**Comment by lmiller1990** [comment]
From what I can see Volar is the go-to now - what does Vetur do that Volar doesn't?

**Comment by johnsoncodehk** [comment]
Volar author is here. 👋 First of all, I'm sorry if I'm uncomfortable discussing Volar here!

Vetur does have some unique features, such as ESLint, highly configurable formatters, Snippets... Volar deliberately avoids adding these features based on some design principles, but at the same time Volar also adds a lot of other unique features, I believe the overall DX is better.

I think currently the most important difference between Vetur and Volar is that Vetur automatically wraps component options with `Vue.extend` internally, while Volar requires the user to explicitly write `Vue.extend` or `defineComponent`. So Vetur's intellisense is richer without wrapping `Vue.extend` or `defineComponent`.

Directly exporting component options is a common practice for some Vue2 and JS users. If you like to export component options directly, or rely on Vetur's unique features, I don't think you need to change your habits, just continue to use Vetur.

**Comment by Hello-Tan** [comment]
You can use volar and then disable the vetur rule.
[look:](https://vuejs.github.io/vetur/reference/#example)
for example
`
// vetur.config.js
module.exports = {
  settings: {
    'vetur.underline.refValue': false,
    'vetur.validation.interpolation': false,
    'vetur.validation.template': false,
    'vetur.validation.style': false,
    'vetur.validation.script': false,
    'vetur.format.defaultFormatter': 'none',
  },
}
`

**Comment by envatic** [comment]
Volar has issues coloring components for javascript **projects.**
and its not my theme. I have tested several, so stop recommending it here
<img width="640" alt="Screen Shot 2022-07-09 at 8 51 30 AM" src="https://user-images.githubusercontent.com/48434697/178093906-56fdffb8-4312-4302-a9d8-b9aa10a76386.png">


**See how vetur handles this**


<img width="573" alt="Screen Shot 2022-07-09 at 9 06 12 AM" src="https://user-images.githubusercontent.com/48434697/178093929-3d733dcc-9d68-4b5c-98d5-f2af38c9dec8.png">

**Comment by envatic** [comment]
A fast way  I solved this is to depend more on eslint for the Js section.  So install eslint  and turn off veturs validation

**turn off this**

<img width="325" alt="Screen Shot 2022-07-09 at 9 12 31 AM" src="https://user-images.githubusercontent.com/48434697/178094127-67ed2c4c-ca43-4720-a0c0-295946e16d65.png">

**Comment by abstrekt** [comment]
Hi

**Comment by fallsimply** [comment]
> Volar has issues coloring components for javascript **projects.**
> and its not my theme. I have tested several, so stop recommending it here
> <img width="640" alt="Screen Shot 2022-07-09 at 8 51 30 AM" src="https://user-images.githubusercontent.com/48434697/178093906-56fdffb8-4312-4302-a9d8-b9aa10a76386.png">
> 
> 
> **See how vetur handles this**
> 
> 
> <img width="573" alt="Screen Shot 2022-07-09 at 9 06 12 AM" src="https://user-images.githubusercontent.com/48434697/178093929-3d733dcc-9d68-4b5c-98d5-f2af38c9dec8.png">
> 
> 

It purposely highlights components differently than html elements. **It's a feature, not a bug.** You could try writing a theme / changing the color token for components in Volar in VSCode JSON Settings

**Comment by boonyasukd** [comment]
FYI, you can now use some Vetur features within Volar 0.36 now, as per @johnsoncodehk 's own [tweet](https://twitter.com/johnsoncodehk/status/1546466364818616320). So going forward the feature gap between the two extensions should be closing.

https://github.com/johnsoncodehk/volar-plugins/tree/master/packages/vetur

**Comment by yoyo930021** [comment]
Fixed in [d89071c](https://github.com/vuejs/vetur/commit/d89071cae0f55fa0b44882f11630fc14dbc194f8)

**Comment by AstralBit** [comment]
> For now can just disable Vetur for script section and use ESlint, TSLint
> 
> VS Code JSON config line `"vetur.validation.script": false,`

great

**Comment by AnthonyDreams** [comment]
This is still happening to me in latest vetur version

**Comment by max13fr** [comment]
> This is still happening to me in latest vetur version

same (in v0.37.3)

**Comment by Sumzibuyu** [comment]
![image](https://github.com/user-attachments/assets/eb50f8c1-8245-4edd-86d6-ffef087a9fb2)

You will still get an error.

**Comment by max13fr** [comment]
> ![image](https://private-user-images.githubusercontent.com/19192294/369044864-eb50f8c1-8245-4edd-86d6-ffef087a9fb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NzQzOTIsIm5iZiI6MTcyNjc3NDA5MiwicGF0aCI6Ii8xOTE5MjI5NC8zNjkwNDQ4NjQtZWI1MGY4YzEtODI0NS00ZWRkLTg2ZDYtZmZlZjA4N2E5ZmIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDE5MjgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyZWY0ZTAxODg5NjQyOWY4Yjg3OTFkZDM0YWFhMzY0ZjFlZTgzY2QzY2I1NWExZGZmZmIzMWJhNDBkZWRjOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tbn2Uy0KeXzjBAwimIUBRfxXTAxMO1uRCgllsjSwkuo)
> 
> You will still get an error.

In your case it's just a typo on your opened div (<d ... instead of <div ...) and components: { ... } should not write like this (not html compliant)
