### ISSUE TITLE
High CPU usage from Vetur extension

### ISSUE THREAD

**Issue by emertechie** [vuejs/vetur#789]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.12.1
- VS Code version: 1.23.1

## Problem

CPU usage is excessively high from the "Code Helper" process. Grabbing the pid from running `top` and using `ps aux | grep 1234`, I can see the process is pointing to vetur extension.

![image](https://user-images.githubusercontent.com/187313/40051896-8354302c-5866-11e8-83a5-86703af3ba05.png)

![image](https://user-images.githubusercontent.com/187313/40051965-c75abf3e-5866-11e8-8e27-99308b42c449.png)

I see someone else has reported something similar here: https://github.com/Microsoft/vscode/issues/49883

**Comment by erodri** [comment]
Downgrading the vetur extension to v0.11.7 seems to fix the issue for me.

**Comment by squalsoft** [comment]
@erodri  How to downgrade extension?

**Comment by prine** [comment]
I have the same issue. It uses up to 200% CPU on my Mac OS X High Sierra 10.13.4. 
Yeah, how is it possible to downgrade? Thanks for the great work btw!

**Comment by cvharris** [comment]
This happened for me after both upgrading Vetur and taking the latest VSCode Insiders. I disabled the extension and reenabled it, seemed to kick it back into normal mode. Not sure if it's just a matter of time before it heats up again.

**Comment by jtr109** [comment]
Same issue for me. 😢

**Comment by erodri** [comment]
@squalsoft @prine I used [this tutorial](https://tpodolak.com/blog/2017/04/09/downgrading-visual-studio-code-extension/) to build the link for the previous vetur extension builds.

For example, the link to v0.11.7 is this: https://octref.gallery.vsassets.io/_apis/public/gallery/publisher/octref/extension/vetur/0.11.7/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

Save it with .vsix extension and install as explained in the tutorial (I just installed it over the current 0.12.1 version).

**Comment by cannap** [comment]
i am not sure but i think its related to https://github.com/vuejs/vetur/issues/774 i think the watcher watches also whole node_modules folder or something like that

**Comment by n0m4dz** [comment]
Same issue here. I have downgraded to previous version (0.11.7 as @erodri mentioned). And it became normal.

**Comment by transtone** [comment]
when installed from vsix, It auto update to 0.12.1.

**Comment by jtr109** [comment]
The suggestion from @erodri works for me.

By the way, don't forget to disable auto updating extension, otherwise the vetur will be updated to 0.12.1 again.

**Comment by HerringtonDarkholme** [comment]
This is probably caused by chokidar file watcher.

Can any one give a reproduction code repo? It will be very helpful.

**Comment by Deguang** [comment]
@HerringtonDarkholme How to get the reproduction code repo？

**Comment by kwando** [comment]
I have this issue also.

**Comment by iamanders** [comment]
Having the same problem since today. @cvharris disable-enable solution did not work for me.

**Comment by mgmgpyaesonewin** [comment]
I am having the same issue. If I type,
```
ps aux | grep 11480
pyaesone         11480 154.5  3.5  3413096 296540   ??  R     2:53PM   0:54.45 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/pyaesone/.vscode/extensions/octref.vetur-0.12.1/node_modules/vscode-languageclient/lib/utils/electronForkStart /Users/pyaesone/.vscode/extensions/octref.vetur-0.12.1/server/dist/vueServerMain.js --node-ipc --clientProcessId=11477
pyaesone         11844   0.0  0.0  2432804   1968 s002  S+    2:53PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn 11480
```

**Comment by sbstnplcn** [comment]
Same issue for me.
another solution is plan instead of downgrade the extension ? 
VS refuse to downgrade it because other extensions depends on it... :(

**Comment by luozhihua** [comment]
Downgrade  is only temporary, when VS reload or reopen, `Vetur` will update to latest automatically.

**Comment by CinKon** [comment]
You can disable automatic plug in updates



Beste Grüße,

Lars Eichler


--
-------------------------------------------------
Lars Eichler
Fichtestr. 33
04275 Leipzig

M +49 178 125 87 19
________________________________

**Comment by HerringtonDarkholme** [comment]
I cannot reproduce the problem in https://github.com/bailicangdu/vue2-elm

Can any one give me a GitHub repository where the problem appear. 

Or your environment if you can reproduce the problem in https://github.com/bailicangdu/vue2-elm ?

**Comment by CinKon** [comment]
The Problem has nothing to do with the code you are writing, but the latest releases of VSCode and Vetur...

**Comment by HerringtonDarkholme** [comment]
@CinKon Please tell me your environment.

![screen shot 2018-05-16 at 6 40 09 pm](https://user-images.githubusercontent.com/2883231/40112466-9c211fac-5938-11e8-9b65-219595057430.png)

**Comment by ch-luke** [comment]
Same here !!! Cpu usage is going crazy since this release.

**Comment by CinKon** [comment]
![bildschirmfoto 2018-05-16 um 12 43 11](https://user-images.githubusercontent.com/3854991/40112570-b7108a0a-5906-11e8-97da-dd7e43aadf64.jpg)

**Comment by Deguang** [comment]
Use VSCoe to open vue2-ele with the latest releases of vetur is fine..... but when i open any .vue file of our private project，cpu usage over 200%  😢。。

**Comment by luozhihua** [comment]
![image](https://user-images.githubusercontent.com/3764249/40112981-6b85984e-593a-11e8-9229-884b4eacb527.png)

When open any `*.vue` files, cup usage of `electron_node vueServerMain.js` is over 140% quickly.

![image](https://user-images.githubusercontent.com/3764249/40113346-bca778b8-593b-11e8-8cd1-64f8ad77c170.png)

**Comment by HerringtonDarkholme** [comment]
@CinKon  @luozhihua  Can you reproduce the problem in https://github.com/bailicangdu/vue2-elm ?

**Comment by CinKon** [comment]
Nope, with vue-elm everything is fine...
Then the problem might be some lint-modules or something else... All my Projects use ESLint and Prettier...

**Comment by Deguang** [comment]
After installed dependencies of vue2-elm ,  reboot vscode  ,open some .vue file 
![image](https://user-images.githubusercontent.com/11596327/40113771-1e218c68-593d-11e8-8e52-ce2cb5cd42fc.png)

**Comment by HerringtonDarkholme** [comment]
Thank @Deguang. But my CPU number is already after dependencies installed.

Would you like to give vetur a profile as documented here? https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions

**Comment by mikerockett** [comment]
On my side, it was between 150% and 200% this morning (SAST), so I disabled it and used another. I just switched back to test, and its averaging 50% now.

**Comment by CinKon** [comment]
[CPU-20180516T113844.837Z.cpuprofile.txt](https://github.com/vuejs/vetur/files/2008904/CPU-20180516T113844.837Z.cpuprofile.txt)

**Comment by Deguang** [comment]
@HerringtonDarkholme  Is this what you want？ 

[CPU-20180516T114234.057Z.cpuprofile.txt](https://github.com/vuejs/vetur/files/2008914/CPU-20180516T114234.057Z.cpuprofile.txt)

**Comment by jtr109** [comment]
The `vue-elm` works well in my environment.

Maybe a problem in import depth in vue components?

**Comment by HerringtonDarkholme** [comment]
Sadly ordinary extension profiling method doesn't work with vetur.

LSP extension has separate process which isn't recorded in default profiling...

**Comment by gonghao** [comment]
Same issue here.

macOS 10.13.5 + VSCode 1.23.1 + Vetur 0.12.1

**Comment by Deguang** [comment]
I have downgraded node from 9.0.0 to 8.8.1, useless....

**Comment by appinteractive** [comment]
same issue here! Even after downgrading to 0.11.7 I get 400% CPU usage but then on Kernel instead of Code Helper.

**Comment by fucazu** [comment]
Same here...
Downgraded to 0.11.8 and still the same high CPU usage.

macOS 10.12.6
node 8.9.1
Code 1.23.1

**Comment by HerringtonDarkholme** [comment]
Profiling the true part of Vetur isn't easy. I will document the method here in hope that some one can help me to analyze the problem.

Vetur is powered by Vue language server, which is executed in a separate VS Code process so you cannot profile it by VSCode's builtin profiler. 

Instead, you have to download and compile vetur yourself. Instruction is here https://github.com/vuejs/vetur/blob/master/docs/CONTRIBUTING.md#code-dev-guide.

After that, you can click the debugger icon in VS Code's left sidebar. Choose debug client. And then a new VS Code window will spawn, open a vue project there. 
![screen shot 2018-05-17 at 10 07 02 am](https://user-images.githubusercontent.com/2883231/40152971-180e7bb0-59ba-11e8-8153-b65aac08841e.png)


Then open output panel, (press ctrl-p and search "toggle output"). Choose Vue Language server. You can see a debug URL in output. 

![screen shot 2018-05-17 at 10 06 02 am](https://user-images.githubusercontent.com/2883231/40152955-057cb804-59ba-11e8-9bc2-29f226b50494.png)

Paste it to chrome and open javascript profiler there. If you cannot see it click the setting button in chrome dev tool and switch on javascript profiler in the more tools menu. Then click start button. Edit your vue project and then end the profiler recording. You can export the profiling and upload it here.

<img width="1504" alt="screen shot 2018-05-17 at 10 07 59 am" src="https://user-images.githubusercontent.com/2883231/40152994-3c113a98-59ba-11e8-8cbe-f113885411f2.png">

**Comment by cycold** [comment]
Same here...
That makes me crazy... 
Have to switch Sublime Text 

macOS 10.12.6 
Vetur 0.12.1
Vscode 1.23.1

![12](https://user-images.githubusercontent.com/2446601/40154014-e727dbfe-59be-11e8-8edf-f56d00bf326b.jpg)

**Comment by HerringtonDarkholme** [comment]
Please make real profiling instead of complaining.

Complaining on Github issue won't help us to solve the problem. If you can provide a repository that reproduce the problem, or you can send me a profiling mentioned above, it will be more beneficial to solving the problem.

**Comment by jtr109** [comment]
@cycold 

Have a try on [the temporary solution above](https://github.com/vuejs/vetur/issues/789#issuecomment-389171763).

The issue will be solved sooner or later.

**Comment by squalsoft** [comment]
This is my front repository which have issue when i open .vue files.
[GuardPortal.WebFront.zip](https://github.com/vuejs/vetur/files/2011930/GuardPortal.WebFront.zip)

**Comment by octref** [comment]
There are a few cases where I can reliably repro this. The file watcher is listening into `node_modules` despite the ignore patterns. Part of the issue is the repeated patterns of `node_modules` of different form on chokidar causing problems for it, other issue is we didn't handle the ignore path on Windows correctly.

I have pushed 1.22.2 which temporarily disables this file watcher. So you might be hitting #355 but otherwise all other features should work fine. I'll fix #355 in another way.

@HerringtonDarkholme I'm looking into using VS Code's own file watcher like this (in `vueMain.ts`)

```ts
  const clientOptions: LanguageClientOptions = {
    documentSelector,
    synchronize: {
      // the settings to synchronize
      configurationSection: ['vetur', 'emmet', 'html', 'javascript', 'typescript', 'prettier', 'stylusSupremacy'],
      // file events that go to `connection.onDidChangeWatchedFiles`
      fileEvents: vscode.workspace.createFileSystemWatcher('{**/*.js,**/*.ts}')
    },
    initializationOptions: {
      config
    },
    revealOutputChannelOn: RevealOutputChannelOn.Never
  };
```

VS Code has a complex solution to file watching (C# + nsfw + chokidar) to expose a consistent file-watching API, so I'd prefer using it. This does mean people consuming VLS need to do their own file-watching on ts/js files, but then the responsibility of managing the overhead of file-watching is on them, not us. (If we do find a cross-platform file-watcher that works reasonably well I don't mind adding it back to VLS).
Another motivation for this is now VLS is still tightly coupled with FS access. I'm working on extracting all FS access into using a [`FileSystemProvider`](https://code.visualstudio.com/updates/v1_23#_filesystem-providers) so Vetur can be used on remote file systems or in browser using a virtual FS.

I'm planning to do some refactoring of `ServiceHost` so it can be accessed by all modes and VLS interface. It'll do file management for all files (vue/js/ts/css/scss/less).

**Comment by octref** [comment]
For others, in simple words, issue should be fixed in 0.12.2. Let me know if it isn't.
You might hit #355, but at least you can use other functionalities fine. #355 will be fixed soon too.

**Comment by HerringtonDarkholme** [comment]
Let's just stick to VS Code's watcher.

I don't think, or at least not have observed, any actual users who use VLS  alone.

**Comment by HerringtonDarkholme** [comment]
@octref Can you give me your reproduction code? I wonder why chokidar fails, at least why fails on MacOS.

**Comment by Deguang** [comment]
@octref still exists...

![image](https://user-images.githubusercontent.com/11596327/40165759-64b0f15c-59ef-11e8-9e90-fe2ae8233ddf.png)

**Comment by erodri** [comment]
Same for me, upgrading to 0.12.2 boosts VSCode CPU use. Reverted to 0.11.7 again.

**Comment by gonzaloserrano** [comment]
Yep, 0.12.2 didn't work here either.

**Comment by wistcc** [comment]
I had to downgrade to 0.11.7 to stop increasing CPU consumption.

**Comment by octref** [comment]
Didn't handle chokidar correctly in 0.12.2. 0.12.3 completely removes chokidar so the problem should be gone. If not, then that's not the file watcher causing the problem.

Would appreciate it if you can confirm 0.12.3 is working for you.

**Comment by Deguang** [comment]
@octref Fixed~! Thanks for your working~
![image](https://user-images.githubusercontent.com/11596327/40191742-ed460a80-5a34-11e8-88a2-4caf4cc4250b.png)

**Comment by faisalraja** [comment]
Worked for me also with 0.12.3.

**Comment by mikerockett** [comment]
Yeah that seems to have done it. 👍

**Comment by erodri** [comment]
Yep, 0.12.3 seems to fix the high CPU usage, thanks!

**Comment by prine** [comment]
Yeah, looks like it's fixed with 0.12.3 👌  
Thanks a lot for the fix and keep up the good work!

**Comment by mgmgpyaesonewin** [comment]
Yay, what a relief!!! Thx.

**Comment by LuisHCK** [comment]
0.12.5 still has high CPU Usage :-1:

**Comment by octref** [comment]
@LuisHCK Would be helpful if you can provide the sample project you are working on, and info such as system spec, OS, node version etc.

**Comment by rabelais88** [comment]
@octref my CPU went full load while working under this condition:
Node: 8.11.3
VSCode: 1.25.1
Vetur: 0.12.6
MacOSX: 10.13.6(High Sierra)
Happened while working on vue-cli v3.0.0 rc3 project, when I changed the current date of MacOSX to 3~4 days earlier than the real date, in order to test user date related problems. VSCode helper took up most of the load but not really sure if it's due to Vetur or other extensions.

**Comment by octref** [comment]
@rabelais88 Try Help -> Process Explorer, and see if Vetur is the issue:

![image](https://user-images.githubusercontent.com/4033249/44042239-9bf71ae0-9ed4-11e8-976b-443bb44a0bf9.png)

**Comment by patzick** [comment]
@octref it appears that problem has unfortunately returned.
Code version: 1.28.2
Vetur version: 0.13.0

<img width="922" alt="screen shot 2018-11-03 at 16 46 22" src="https://user-images.githubusercontent.com/13100280/47954326-5b4bad80-df89-11e8-9e35-a73247568a53.png">

**Comment by octref** [comment]
@patzick Please open a new issue. Also, is it possible for me to get a repro case? Can you modify https://github.com/octref/veturpack to repro the issue?
Also how large is your project?

**Comment by patzick** [comment]
@octref problem has disappeared after two days, i don't know why but it's okey now. Thank you, vetur is great! :)

**Comment by CaptainMack** [comment]
I am having same problem, Code Helper running 100% using 

´ps aux | grep <Code Helper PID>´ 

I get the following:

`Helper.app/Contents/MacOS/Code Helper /Users/Name/.vscode/extensions/octref.vetur-0.14.2/server/dist/vueServerMain.js --node-ipc --clientProcessId=16278`

**Comment by MatanYed** [comment]
same here vetur 0.14.5

**Comment by marvinside** [comment]
Not sure if this is the same bug or a different one as this Issue is mostly affecting OSX users.

After having VS-Code running for 1-2 Days, the reaction time as i type gets pretty bad. Sometimes it takes 1-2 seconds till the pressed character appears in VS-Code.

I noticed high CPU usage of Vetur as i type, mostly peaking at 90% CPU.
After restarting VS-Code, the Problem is fixed. Maybe it's a MemoryLeak, also wondering why vs-code's bootstrap-fork process is having 190G of virtual memory...

![bildschirmfoto von 2019-02-09 15-34-49](https://user-images.githubusercontent.com/3470697/52522095-0bb00880-2c81-11e9-94f5-e6a5c9203b89.png)

**Comment by octref** [comment]
@marvinside That's actually a problem of VS Code, not Vetur. I created an issue on VS Code side: https://github.com/Microsoft/vscode/issues/68322. It would be great if you can follow up with some more details so we can fix it. Thanks!

**Comment by marvinside** [comment]
@octref I'm not sure if this is the problem, as that process has not gotten any CPU usage while VS-Code slows down.

**Comment by vividvilla** [comment]
VSCode is literally unusable for Vue project in macOS because of this bug.

**Comment by octref** [comment]
@vividvilla Create new issue following https://github.com/vuejs/vetur/blob/master/.github/PERF_ISSUE.md.

**Comment by kjleitz** [comment]
@octref Just a stab in the dark:

Could this be related to the problems which precipitated [ForkTsCheckerWebpackPlugin](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin#readme)? Obviously _this_ issue is unrelated to webpack, but we ended up switching to the `fork-ts-checker-webpack-plugin` a while ago because our builds were taking > 15 minutes and it reduced them to < 4 minutes. IIRC it was because the type checking service was being restarted for each SFC that the Vue template compiler consumed, and had to walk the import tree separately for _every single SFC_ and wasn't caching the hits between runs, so it had to hit the filesystem repeatedly for module resolutions.

I don't know the specifics or internals of VSCode's file watching service, or Vetur itself, but as the project gained more files (especially more entry points/"close to root level" components) the compilation time (and type checking) took longer and longer because the compilation of the SFCs were spawning a huge redundancy in file reads. That seems to also be the case (in my experience) with this Vetur issue, as it doesn't have nearly the same slowdown in a small project as it does in a moderately larger project.

Could it be the same root cause? And would a similar strategy (forking the type checking service or other module-resolving services into their own thread/process so they can take advantage of caching between runs) possibly mitigate the issue?

**Comment by octref** [comment]
@kjleitz You are correct the module resolution is not cached and optimized. I opened https://github.com/vuejs/vetur/issues/1286 to work on it but didn't finish before I went to vacation. I'll get back to it.

**Comment by kjleitz** [comment]
@octref 😍 👍
